### PR TITLE
Add armv6 release

### LINKED ISSUE #68: [ARMv6] Installation problem
I am trying to install os-agent on raspbarry pi 1 model b which has armv6 architecture.
I use the version for armv7 and I get the following error:
err_installation

Looking at the log the error is as follows:
log_installation

The error is a result of trying to use your ARMv7 binary on ARMv6. All the quad-core Pi’s (2, 3 and 3+) are v7 while the single-core (A, B, and Zero) are v6. Installation works fine since Raspbian is “armhf”, however the binary will get a SIGKILL due to illegal instructions.

Could you please make the binary ARMv6 compatible to allow use on all Raspberry Pi’s?

### PR DESCRIPTION
**Pull request by neopi21**
Add armv6 release (for RPi 1b ie.)

fixes #68

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @neopi21, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;os-agent#87).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by neopi21** [comment]
> 

I did it

**Comment by frenck** [comment]
@neopi21 But you can just use the v5 in those cases?

**Comment by neopi21** [comment]
> @neopi21 But you can just use the v5 in those cases?

???

**Comment by frenck** [comment]
> ???

I'm not entirely sure what you are trying to tell by those question marks, but the ARMv5 provided binaries will work on those devices.

**Comment by Lobochobo** [comment]
Dear Home Assistant,
This is my first ever comment/request on GitHub to Home Assistant. 
Kindly provide the Home Assistant OS-Agent **os-agent_1.2.2_linux_armv6.deb** that should be on the page **https://github.com/home-assistant/os-agent/releases/tag/1.2.2**.

When I try to use/install os-agent_1.2.2_linux_armv5.deb [five] on a RasPi 1B+ ARMv6 it responds with the following error:
sudo dpkg -i os-agent_1.2.2_linux_armv5.deb
dpkg: error processing archive os-agent_1.2.2_linux_armv5.deb (--install):
 package architecture (armel) does not match system (armhf)
Errors were encountered while processing:
 os-agent_1.2.2_linux_armv5.deb

So this ARMv5 (ARMEL) is not usable.
Waiting on your reply I remain.

Many thanks in advance,

**Comment by Tony2k** [comment]
Add Odroid C4 please

**Comment by slimak-69** [comment]
R

**Review by frenck — APPROVED** [review]
Thanks, @neopi21 👍

**Pull request merged**
